name: Test
on: [pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.23.x, 1.24.x]
        venv: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.venv }}
    steps:
    - name: Install Go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Run tests
      working-directory: src
      run: go test -v ./...

  conclusion:
    name: conclusion
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Result
        run: ${{ needs.test.result == 'success' }}
